/**
 * icon-map.ts — Static mapping from icon name strings to Lucide icon components.
 * Used by NodeIcon to render goal/job icons by name.
 * The LLM icon-picker in the agent picks from this same set of names.
 */

import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  BarChart2,
  Bell,
  BookOpen,
  Box,
  Briefcase,
  Bug,
  Building2,
  CheckCircle2,
  ClipboardList,
  Cloud,
  Code2,
  Cpu,
  Database,
  Eye,
  FileText,
  Flag,
  FlaskConical,
  Folder,
  Globe,
  HardDrive,
  Hash,
  Key,
  Layers,
  LineChart,
  Link,
  Lock,
  Mail,
  MessageSquare,
  Network,
  Package,
  Paintbrush,
  Play,
  RefreshCw,
  Rocket,
  Search,
  Server,
  Settings2,
  Shield,
  Star,
  Tag,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  Users,
  Wrench,
  Zap,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  activity: Activity,
  alert: AlertTriangle,
  chart: BarChart2,
  bell: Bell,
  book: BookOpen,
  box: Box,
  briefcase: Briefcase,
  bug: Bug,
  building: Building2,
  check: CheckCircle2,
  clipboard: ClipboardList,
  cloud: Cloud,
  code: Code2,
  cpu: Cpu,
  database: Database,
  eye: Eye,
  file: FileText,
  flag: Flag,
  flask: FlaskConical,
  folder: Folder,
  globe: Globe,
  hard_drive: HardDrive,
  hash: Hash,
  key: Key,
  layers: Layers,
  line_chart: LineChart,
  link: Link,
  lock: Lock,
  mail: Mail,
  message: MessageSquare,
  network: Network,
  package: Package,
  paintbrush: Paintbrush,
  play: Play,
  refresh: RefreshCw,
  rocket: Rocket,
  search: Search,
  server: Server,
  settings: Settings2,
  shield: Shield,
  star: Star,
  tag: Tag,
  target: Target,
  timer: Timer,
  trending: TrendingUp,
  trophy: Trophy,
  users: Users,
  wrench: Wrench,
  zap: Zap,
};

/** All valid icon name keys — passed to the LLM so it picks a valid option. */
export const ICON_NAMES = Object.keys(ICON_MAP);
