import { registerProjectHandlers } from "./projects.js";
import { registerGoalHandlers } from "./goals.js";
import { registerJobHandlers } from "./jobs.js";
import { registerRunHandlers } from "./runs.js";
import { registerSettingHandlers } from "./settings.js";
import { registerClaudeCodeHandlers } from "./claude-code.js";
import { registerSchedulerHandlers } from "./scheduler.js";
import { registerChatHandlers } from "./chat.js";
import { registerDashboardHandlers } from "./dashboard.js";
import { registerMemoryHandlers } from "./memories.js";
import { registerDataHandlers } from "./data.js";
import { registerPowerHandlers } from "./power.js";
import { registerLicenseHandlers } from "./license.js";
import { registerPermissionHandlers } from "./permissions.js";
import { registerCredentialHandlers } from "./credentials.js";
import { registerAutopilotHandlers } from "./autopilot.js";
import { registerBrowserMcpHandlers } from "./browser-mcp.js";
import { registerDataTableHandlers } from "./data-tables.js";
import { registerTargetHandlers } from "./targets.js";
import { registerVisualizationHandlers } from "./visualizations.js";
import { registerUsageHandlers } from "./usage.js";
/** Register all domain IPC handlers */
export function registerAllHandlers() {
  registerProjectHandlers();
  registerGoalHandlers();
  registerJobHandlers();
  registerRunHandlers();
  registerSettingHandlers();
  registerClaudeCodeHandlers();
  registerSchedulerHandlers();
  registerChatHandlers();
  registerDashboardHandlers();
  registerMemoryHandlers();
  registerDataHandlers();
  registerPowerHandlers();
  registerLicenseHandlers();
  registerPermissionHandlers();
  registerCredentialHandlers();
  registerAutopilotHandlers();
  registerBrowserMcpHandlers();
  registerDataTableHandlers();
  registerTargetHandlers();
  registerVisualizationHandlers();
  registerUsageHandlers();
}
