import type { ServiceCatalogueEntry } from "@openhelm/shared";

/** Services in the developer / infra / data spaces. Split from the main catalogue to keep files small. */
export const DEV_AND_INFRA_SERVICES: ServiceCatalogueEntry[] = [
  { id: "github", name: "GitHub", aliases: ["github.com", "gh"], domain: "github.com", category: "dev", description: "Code hosting, pull requests, CI", hasMcp: true, mcpServerId: "com.github/mcp", mcpInstallCommand: ["npx", "-y", "@modelcontextprotocol/server-github"], mcpOauthRequired: true, hasCli: true, cliId: "gh" },
  { id: "gitlab", name: "GitLab", aliases: ["gitlab.com"], domain: "gitlab.com", category: "dev", description: "Git hosting with built-in CI/CD", hasCli: false },
  { id: "bitbucket", name: "Bitbucket", aliases: ["bitbucket.org"], domain: "bitbucket.org", category: "dev", description: "Atlassian Git hosting" },
  { id: "vercel", name: "Vercel", aliases: ["vercel.com"], domain: "vercel.com", category: "infra", description: "Frontend deployment platform", hasCli: true, cliId: "vercel" },
  { id: "netlify", name: "Netlify", aliases: ["netlify.com"], domain: "netlify.com", category: "infra", description: "Static site hosting and edge functions" },
  { id: "cloudflare", name: "Cloudflare", aliases: ["cloudflare.com", "wrangler"], domain: "cloudflare.com", category: "infra", description: "CDN, DNS, Workers, R2" },
  { id: "aws", name: "AWS", aliases: ["amazon web services", "aws.amazon.com"], domain: "aws.amazon.com", iconSlug: "amazonaws", category: "infra", description: "Amazon Web Services", hasCli: true, cliId: "aws" },
  { id: "gcp", name: "Google Cloud", aliases: ["gcloud", "google cloud platform"], domain: "cloud.google.com", iconSlug: "googlecloud", category: "infra", description: "Google Cloud Platform", hasCli: true, cliId: "gcloud" },
  { id: "azure", name: "Azure", aliases: ["microsoft azure", "azure.com"], domain: "azure.microsoft.com", iconSlug: "microsoftazure", category: "infra", description: "Microsoft's cloud platform" },
  { id: "fly", name: "Fly.io", aliases: ["flyctl", "fly.io"], domain: "fly.io", iconSlug: "flydotio", category: "infra", description: "Edge app deployment", hasCli: true, cliId: "fly" },
  { id: "railway", name: "Railway", aliases: ["railway.app"], domain: "railway.app", category: "infra", description: "App deployment platform", hasCli: true, cliId: "railway" },
  { id: "render", name: "Render", aliases: ["render.com"], domain: "render.com", category: "infra", description: "Cloud hosting for apps and databases" },
  { id: "heroku", name: "Heroku", aliases: ["heroku.com"], domain: "heroku.com", category: "infra", description: "App platform" },
  { id: "digitalocean", name: "DigitalOcean", aliases: ["digitalocean.com"], domain: "digitalocean.com", category: "infra", description: "Cloud VPS hosting" },
  { id: "supabase", name: "Supabase", aliases: ["supabase.com"], domain: "supabase.com", category: "data", description: "Postgres, auth, storage, edge functions", hasMcp: true, mcpServerId: "com.supabase/mcp", mcpInstallCommand: ["npx", "-y", "@supabase/mcp-server-supabase@latest"], mcpOauthRequired: true, hasCli: true, cliId: "supabase" },
  { id: "postgres", name: "PostgreSQL", aliases: ["postgresql", "pg"], iconSlug: "postgresql", category: "data", description: "Open-source relational database" },
  { id: "mysql", name: "MySQL", aliases: ["mysql.com"], category: "data", description: "Open-source relational database" },
  { id: "mongodb", name: "MongoDB", aliases: ["mongo", "atlas"], domain: "mongodb.com", category: "data", description: "Document database" },
  { id: "redis", name: "Redis", aliases: ["redis.io"], domain: "redis.io", category: "data", description: "In-memory data store" },
  { id: "snowflake", name: "Snowflake", aliases: ["snowflake.com"], domain: "snowflake.com", category: "data", description: "Cloud data warehouse" },
  { id: "bigquery", name: "BigQuery", aliases: ["google bigquery"], domain: "cloud.google.com/bigquery", iconSlug: "googlebigquery", category: "data", description: "Google's serverless data warehouse" },
  { id: "databricks", name: "Databricks", domain: "databricks.com", category: "data", description: "Unified analytics platform" },
  { id: "sentry", name: "Sentry", domain: "sentry.io", category: "dev", description: "Error tracking and performance", hasMcp: true, mcpServerId: "com.sentry/mcp", mcpInstallCommand: ["uvx", "sentry-mcp"], mcpOauthRequired: true },
  { id: "datadog", name: "Datadog", aliases: ["datadoghq"], domain: "datadoghq.com", category: "infra", description: "Monitoring and observability" },
  { id: "posthog", name: "PostHog", aliases: ["posthog.com"], domain: "posthog.com", category: "data", description: "Product analytics" },
  { id: "mixpanel", name: "Mixpanel", domain: "mixpanel.com", category: "data", description: "Product analytics" },
  { id: "amplitude", name: "Amplitude", domain: "amplitude.com", category: "data", description: "Product analytics" },
  { id: "segment", name: "Segment", aliases: ["segment.io"], domain: "segment.com", category: "data", description: "Customer data platform" },
  { id: "stripe", name: "Stripe", domain: "stripe.com", category: "infra", description: "Payments and financial infrastructure", hasCli: true, cliId: "stripe" },
  { id: "twilio", name: "Twilio", domain: "twilio.com", category: "infra", description: "SMS, voice, email APIs" },
  { id: "sendgrid", name: "SendGrid", domain: "sendgrid.com", category: "infra", description: "Email delivery API" },
  { id: "resend", name: "Resend", domain: "resend.com", category: "infra", description: "Developer-focused email API" },
  { id: "mailchimp", name: "Mailchimp", domain: "mailchimp.com", category: "comms", description: "Email marketing platform" },
  { id: "pagerduty", name: "PagerDuty", domain: "pagerduty.com", category: "infra", description: "Incident response" },
  { id: "auth0", name: "Auth0", domain: "auth0.com", category: "infra", description: "Identity and auth platform" },
  { id: "clerk", name: "Clerk", domain: "clerk.com", category: "infra", description: "User management and auth" },
  { id: "firebase", name: "Firebase", domain: "firebase.google.com", category: "infra", description: "Google's app development backend" },
  { id: "docker", name: "Docker Hub", aliases: ["docker", "dockerhub"], domain: "hub.docker.com", category: "dev", description: "Container image registry" },
  { id: "npm", name: "npm", aliases: ["npmjs"], domain: "npmjs.com", category: "dev", description: "JavaScript package registry" },
  { id: "pypi", name: "PyPI", aliases: ["python package index"], domain: "pypi.org", category: "dev", description: "Python package index" },
];
