import type { ServiceCatalogueEntry } from "@openhelm/shared";

/** Productivity, comms, design, AI, and misc services. */
export const PRODUCTIVITY_AND_COMMS_SERVICES: ServiceCatalogueEntry[] = [
  { id: "notion", name: "Notion", aliases: ["notion.so"], domain: "notion.com", category: "productivity", description: "All-in-one workspace for notes, docs, databases", hasMcp: true, mcpServerId: "com.notion/mcp", mcpInstallCommand: ["npx", "-y", "@notionhq/mcp"], mcpOauthRequired: true },
  { id: "linear", name: "Linear", domain: "linear.app", category: "productivity", description: "Issue tracking built for modern software teams", hasMcp: true, mcpServerId: "com.linear/mcp", mcpOauthRequired: true },
  { id: "jira", name: "Jira", aliases: ["atlassian"], domain: "atlassian.com/software/jira", iconSlug: "jira", category: "productivity", description: "Atlassian's issue tracking and project management" },
  { id: "confluence", name: "Confluence", domain: "atlassian.com/software/confluence", category: "productivity", description: "Atlassian team workspace" },
  { id: "asana", name: "Asana", domain: "asana.com", category: "productivity", description: "Team project management" },
  { id: "trello", name: "Trello", domain: "trello.com", category: "productivity", description: "Kanban-style project boards" },
  { id: "clickup", name: "ClickUp", domain: "clickup.com", category: "productivity", description: "All-in-one productivity platform" },
  { id: "airtable", name: "Airtable", domain: "airtable.com", category: "productivity", description: "Spreadsheet-database hybrid" },
  { id: "monday", name: "monday.com", aliases: ["monday"], domain: "monday.com", iconSlug: "mondaydotcom", category: "productivity", description: "Work operating system" },
  { id: "evernote", name: "Evernote", domain: "evernote.com", category: "productivity", description: "Note-taking app" },
  { id: "obsidian", name: "Obsidian", domain: "obsidian.md", category: "productivity", description: "Markdown knowledge base" },
  { id: "google-drive", name: "Google Drive", aliases: ["gdrive"], domain: "drive.google.com", iconSlug: "googledrive", category: "productivity", description: "Google's cloud file storage" },
  { id: "dropbox", name: "Dropbox", domain: "dropbox.com", category: "productivity", description: "Cloud file storage and sync" },
  { id: "box", name: "Box", domain: "box.com", category: "productivity", description: "Enterprise cloud content management" },
  { id: "google-docs", name: "Google Docs", domain: "docs.google.com", iconSlug: "googledocs", category: "productivity", description: "Collaborative document editor" },
  { id: "google-sheets", name: "Google Sheets", domain: "sheets.google.com", iconSlug: "googlesheets", category: "productivity", description: "Collaborative spreadsheets" },
  { id: "google-calendar", name: "Google Calendar", aliases: ["gcal"], domain: "calendar.google.com", iconSlug: "googlecalendar", category: "productivity", description: "Calendar and scheduling" },
  { id: "gmail", name: "Gmail", domain: "mail.google.com", category: "comms", description: "Google's email service" },
  { id: "outlook", name: "Outlook", aliases: ["microsoft outlook"], domain: "outlook.com", iconSlug: "microsoftoutlook", category: "comms", description: "Microsoft's email and calendar" },
  { id: "slack", name: "Slack", domain: "slack.com", category: "comms", description: "Team messaging", hasMcp: true, mcpServerId: "com.slack/mcp", mcpInstallCommand: ["npx", "-y", "@slack/mcp-server"], mcpOauthRequired: true },
  { id: "discord", name: "Discord", domain: "discord.com", category: "comms", description: "Voice, video, and text chat for communities" },
  { id: "microsoft-teams", name: "Microsoft Teams", aliases: ["teams"], domain: "teams.microsoft.com", iconSlug: "microsoftteams", category: "comms", description: "Microsoft's team collaboration hub" },
  { id: "zoom", name: "Zoom", domain: "zoom.us", category: "comms", description: "Video conferencing" },
  { id: "telegram", name: "Telegram", domain: "telegram.org", category: "comms", description: "Messaging app" },
  { id: "whatsapp", name: "WhatsApp", domain: "whatsapp.com", category: "comms", description: "Messaging app" },
  { id: "signal", name: "Signal", domain: "signal.org", category: "comms", description: "Private messaging" },
  { id: "x-twitter", name: "X (Twitter)", aliases: ["x", "x.com", "twitter"], domain: "x.com", iconSlug: "x", category: "comms", description: "Microblogging and social network" },
  { id: "reddit", name: "Reddit", domain: "reddit.com", category: "comms", description: "Community discussion platform" },
  { id: "linkedin", name: "LinkedIn", domain: "linkedin.com", category: "comms", description: "Professional networking" },
  { id: "facebook", name: "Facebook", domain: "facebook.com", category: "comms", description: "Social network" },
  { id: "instagram", name: "Instagram", domain: "instagram.com", category: "comms", description: "Photo and video social network" },
  { id: "tiktok", name: "TikTok", domain: "tiktok.com", category: "comms", description: "Short-form video platform" },
  { id: "youtube", name: "YouTube", domain: "youtube.com", category: "comms", description: "Video sharing platform" },
  { id: "hackernews", name: "Hacker News", aliases: ["hn", "ycombinator"], domain: "news.ycombinator.com", iconSlug: "ycombinator", category: "comms", description: "Tech news and community" },
  { id: "figma", name: "Figma", domain: "figma.com", category: "design", description: "Collaborative design tool" },
  { id: "canva", name: "Canva", domain: "canva.com", category: "design", description: "Visual design platform" },
  { id: "sketch", name: "Sketch", domain: "sketch.com", category: "design", description: "Mac-native design tool" },
  { id: "adobe", name: "Adobe Creative Cloud", aliases: ["adobe cc"], domain: "adobe.com", iconSlug: "adobecreativecloud", category: "design", description: "Adobe's creative suite" },
  { id: "openai", name: "OpenAI", aliases: ["chatgpt"], domain: "openai.com", category: "ai", description: "ChatGPT and the OpenAI API" },
  { id: "anthropic", name: "Anthropic", aliases: ["claude"], domain: "anthropic.com", category: "ai", description: "Claude API and console" },
  { id: "huggingface", name: "Hugging Face", aliases: ["hf"], domain: "huggingface.co", category: "ai", description: "ML model hub and datasets" },
  { id: "perplexity", name: "Perplexity", domain: "perplexity.ai", category: "ai", description: "AI answer engine" },
  { id: "pipedream", name: "Pipedream", domain: "pipedream.com", category: "dev", description: "Workflow automation", hasMcp: true, mcpServerId: "com.pipedream/mcp", mcpOauthRequired: true },
  { id: "zapier", name: "Zapier", domain: "zapier.com", category: "dev", description: "Workflow automation" },
  { id: "make", name: "Make", aliases: ["integromat"], domain: "make.com", iconSlug: "make", category: "dev", description: "Visual workflow automation" },
  { id: "shopify", name: "Shopify", domain: "shopify.com", category: "other", description: "E-commerce platform" },
  { id: "hubspot", name: "HubSpot", domain: "hubspot.com", category: "other", description: "CRM and marketing" },
  { id: "salesforce", name: "Salesforce", domain: "salesforce.com", category: "other", description: "CRM platform" },
  { id: "intercom", name: "Intercom", domain: "intercom.com", category: "comms", description: "Customer messaging" },
  { id: "zendesk", name: "Zendesk", domain: "zendesk.com", category: "comms", description: "Customer support platform" },
  { id: "calendly", name: "Calendly", domain: "calendly.com", category: "productivity", description: "Scheduling automation" },
];
