/**
 * Autopilot Orchestrator — manages the lifecycle of system jobs.
 *
 * Two layers of autonomy, both gated by the autopilot_mode setting:
 * - Tactical: per-run self-correction (handled in executor/self-correction.ts)
 * - Strategic: system-generated monitoring/review jobs (handled here)
 *
 * Modes:
 * - full_auto: system jobs created and run without approval
 * - approval_required: system jobs proposed via dashboard for user review
 * - off: no system jobs, no self-correction
 */

import { getSetting, setSetting, deleteSetting } from "../db/queries/settings.js";
import { createJob, listSystemJobsForGoal, listJobs } from "../db/queries/jobs.js";
import { createProposal } from "../db/queries/autopilot-proposals.js";
import { getGoal, listGoals } from "../db/queries/goals.js";
import { generateSystemJobs } from "../planner/system-jobs.js";
import { emit } from "../ipc/emitter.js";
import type { AutopilotMode } from "@openhelm/shared";

const VALID_AUTOPILOT_MODES: AutopilotMode[] = [
  "full_auto",
  "approval_required",
  "off",
];
const BACKFILL_COOLDOWN_MS = 24 * 60 * 60 * 1000; // 24 hours

// ─── Cooldown tracking ───

interface BackfillFailureMap {
  [goalId: string]: number;
}

function getBackfillFailures(): BackfillFailureMap {
  const setting = getSetting("autopilot_backfill_failures");
  if (!setting?.value) return {};
  try {
    return JSON.parse(setting.value) as BackfillFailureMap;
  } catch {
    return {};
  }
}

function recordBackfillFailure(goalId: string): void {
  const map = getBackfillFailures();
  map[goalId] = Date.now();
  setSetting("autopilot_backfill_failures", JSON.stringify(map));
}

function isOnCooldown(goalId: string): boolean {
  const map = getBackfillFailures();
  const failedAt = map[goalId];
  if (!failedAt) return false;
  return Date.now() - failedAt < BACKFILL_COOLDOWN_MS;
}

/** Clear cooldown for a goal (called on manual regeneration). */
export function clearBackfillCooldown(goalId: string): void {
  const map = getBackfillFailures();
  delete map[goalId];
  if (Object.keys(map).length === 0) {
    deleteSetting("autopilot_backfill_failures");
  } else {
    setSetting("autopilot_backfill_failures", JSON.stringify(map));
  }
}

// ─── Context check ───

function hasEnoughContext(
  goalId: string,
  goalName: string,
  goalDescription: string,
): boolean {
  const desc = goalDescription.trim();
  if (desc.length > 0 && desc !== goalName.trim()) return true;
  const userJobs = listJobs({ goalId }).filter((j) => j.source === "user");
  return userJobs.length > 0;
}

// ─── Mode ───

/** Get the current autopilot mode (defaults to full_auto if not set) */
export function getAutopilotMode(): AutopilotMode {
  const setting = getSetting("autopilot_mode");
  if (!setting?.value) return "full_auto";
  if (VALID_AUTOPILOT_MODES.includes(setting.value as AutopilotMode)) {
    return setting.value as AutopilotMode;
  }
  console.error(
    `[autopilot] unrecognised autopilot_mode value "${setting.value}", defaulting to "off"`,
  );
  return "off";
}

// ─── Event helpers ───

function emitGenerationFailed(
  goalId: string,
  projectId: string,
  error: unknown,
): void {
  const goal = getGoal(goalId);
  const errorStr = error instanceof Error ? error.message : String(error);
  const isOpaque =
    errorStr.includes("exited with code") && !errorStr.includes(":");
  const hint = isOpaque
    ? "Try adding a description to this goal, or create some jobs first."
    : "";
  emit("autopilot.generationFailed", {
    goalId,
    projectId,
    goalName: goal?.name ?? "Unknown goal",
    error: errorStr,
    hint,
  });
}

// ─── Generation ───

/**
 * Generate and handle system jobs for a goal.
 * Called after goal creation (IPC, chat, or backfill).
 */
export async function generateAndHandleSystemJobs(
  goalId: string,
  projectId: string,
): Promise<void> {
  const mode = getAutopilotMode();
  if (mode === "off") return;

  try {
    const systemJobs = await generateSystemJobs(goalId, projectId);
    if (systemJobs.length === 0) {
      console.error("[autopilot] no system jobs generated for goal", goalId);
      emitGenerationFailed(
        goalId,
        projectId,
        "No system jobs were generated by the LLM",
      );
      recordBackfillFailure(goalId);
      return;
    }

    if (mode === "full_auto") {
      const jobIds: string[] = [];
      for (const sj of systemJobs) {
        const job = createJob({
          projectId,
          goalId,
          name: sj.name,
          description: sj.description,
          prompt: sj.prompt,
          scheduleType: sj.scheduleType,
          scheduleConfig: sj.scheduleConfig,
          source: "system",
          systemCategory: sj.systemCategory,
          model: "haiku",
          modelEffort: "low",
        });
        jobIds.push(job.id);
      }
      console.error(
        `[autopilot] created ${jobIds.length} system jobs for goal ${goalId}`,
      );
      emit("autopilot.systemJobsCreated", { goalId, jobIds });
    } else if (mode === "approval_required") {
      const proposal = createProposal({
        goalId,
        projectId,
        plannedJobs: systemJobs,
        reason: `Generated ${systemJobs.length} monitoring job(s) to help track progress and health for this goal.`,
      });
      console.error(
        `[autopilot] created proposal ${proposal.id} for goal ${goalId}`,
      );
      emit("autopilot.proposalCreated", {
        proposalId: proposal.id,
        goalId,
      });
    }
  } catch (err) {
    console.error("[autopilot] failed to generate system jobs:", err);
    recordBackfillFailure(goalId);
    emitGenerationFailed(goalId, projectId, err);
  }
}

// ─── Backfill ───

/**
 * Backfill system jobs for active goals that don't have any.
 * Called once at agent startup. Skips goals on cooldown (failed
 * within last 24h) and goals with insufficient context.
 */
export async function backfillMissingAutopilotJobs(): Promise<void> {
  const mode = getAutopilotMode();
  if (mode === "off") return;

  const activeGoals = listGoals({ status: "active" });
  let backfilled = 0;
  let skippedCooldown = 0;
  let skippedThin = 0;

  for (const goal of activeGoals) {
    const existing = listSystemJobsForGoal(goal.id);
    if (existing.length > 0) continue;

    if (isOnCooldown(goal.id)) {
      skippedCooldown++;
      continue;
    }

    if (!hasEnoughContext(goal.id, goal.name, goal.description)) {
      skippedThin++;
      console.error(
        `[autopilot] skipping backfill for goal "${goal.name}" (${goal.id}): insufficient context`,
      );
      continue;
    }

    console.error(
      `[autopilot] backfilling system jobs for goal "${goal.name}" (${goal.id})`,
    );
    try {
      await generateAndHandleSystemJobs(goal.id, goal.projectId);
      backfilled++;
    } catch (err) {
      console.error(
        `[autopilot] backfill failed for goal ${goal.id}:`,
        err,
      );
    }
  }

  if (backfilled > 0 || skippedCooldown > 0 || skippedThin > 0) {
    console.error(
      `[autopilot] backfill complete: ${backfilled} generated, ${skippedCooldown} on cooldown, ${skippedThin} insufficient context`,
    );
  }
}
